services:
  - type: web
    name: chronobot
    runtime: python
    runtimeVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SHEET_ID
        sync: false
      - key: CREDENTIALS_JSON
        sync: false
      - key: PORT
        value: 10000